# Generated by Django 5.0.1 on 2024-02-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdetails',
            name='photo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
