# Generated by Django 5.0.1 on 2024-02-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_formdetails_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdetails',
            old_name='userId',
            new_name='user',
        ),
    ]
