# Generated by Django 4.2.7 on 2024-02-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_formdetails_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdetails',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formdetails',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
