# Generated by Django 4.2.7 on 2024-02-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_formdetails_mobile_alter_formdetails_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdetails',
            name='address',
            field=models.TextField(),
        ),
    ]
